apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: jerryjohnson/crud_api:v1.01
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: '256Mi'
            cpu: '250m'
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: '5000'
          - name: DB_NAME
            value: 'crud_db'
          - name: DB_PASSWORD
            value: '0123456789'
          - name: DB_USERNAME
            value: 'root'
          - name: DB_HOST
            value: 'mysql'
          - name: DB_PORT
            value: '3306'
